#:schema node_modules/wrangler/config-schema.json
name = "api-hono-template"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[observability]
enabled = true

[[d1_databases]]
binding = "DATABASE" # i.e. available in your Worker on env.DB
database_name = "d1-example-server"
database_id = ""
